version: '3.8'

services:
  dill-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dill-monitor
    restart: unless-stopped
    ports:
      - '19090:9090'
    volumes:
      - ./config:/app/config
    networks:
      - dill-network

networks:
  dill-network:
    driver: bridge
